name = "aggregate_content"
main = "src/index.js"
compatibility_date = "2023-07-19"

kv_namespaces = [{ binding = "CONNPASS_PROXY_KV", id = "e765cdcb097644e49ddffe726a9586fc" }]

[triggers]
crons = [ "*/15 * * * *" ]
